export const TEXTS = {
  // Navigation
  NAV_LOGO: "Bookshelf",
  NAV_LOGO_PREFIX: "Booksh",
  NAV_LOGO_SUFFIX: "elf",
  NAV_BOOKS: "Books",
  NAV_COLLECTIONS: "My Shelf",
  NAV_LOGIN: "Login",
  NAV_LOGOUT: "Logout",
  NAV_REGISTER: "Register",
  NAV_CREATE: "Create",
  NAV_CHAT: "Support Chat",
  NAV_SEARCH_TRIGGER: "Search book or author...",
  NAV_GUEST: "Guest",
  // Auth
  AUTH_LOGIN_HEADING: "Welcome back",
  AUTH_LOGIN_SUBTITLE: "Sign in to your bookshelf",
  AUTH_REGISTER_HEADING: "Create account",
  AUTH_REGISTER_SUBTITLE: "Start tracking your reading",
  AUTH_TAB_LOGIN: "Login",
  AUTH_TAB_REGISTER: "Register",
  AUTH_BTN_LOGIN: "Sign in",
  AUTH_BTN_REGISTER: "Create account",
  AUTH_EMAIL_LINK: "Sign in with email link",
  AUTH_OR_DIVIDER: "or",
  AUTH_TERMS: "By signing in, you accept our",
  AUTH_TERMS_LINK: "Terms of Service",
  AUTH_LABEL_EMAIL: "Email",
  AUTH_LABEL_PASSWORD: "Password",
  AUTH_LABEL_YEAR: "Birth year",
  AUTH_PLACEHOLDER_EMAIL: "name@example.com",
  AUTH_PLACEHOLDER_PASSWORD: "••••••••",
  AUTH_PLACEHOLDER_YEAR: "e.g. 1990",
  AUTH_LOGIN_TAGLINE: "Track every book,\nyou read\nor want to.",
  AUTH_LOGIN_QUOTE:
    "Track what you have read, plan the next one, share with friends.",
  AUTH_REGISTER_TAGLINE: "Start your\nreading\njourney.",
  // Catalog
  CATALOG_TITLE: "Book Catalog",
  CATALOG_SUBTITLE: "Find your next favourite book",
  CATALOG_SEARCH_PLACEHOLDER: "Search by title or author...",
  CATALOG_EMPTY: "No books found.",
  CATALOG_FILTER_ALL: "All",
  // Book Detail
  DETAIL_BACK: "← Back to catalog",
  DETAIL_PAGES: "Pages",
  DETAIL_YEAR: "Year",
  DETAIL_RATING: "Rating",
  DETAIL_ADD_TO_SHELF: "Add to my shelf",
  DETAIL_SHARE_LABEL: "View a friend's shelf",
  DETAIL_SHARE_PLACEHOLDER: "friend@example.com",
  DETAIL_SHARE_BTN: "View shelf",
  DETAIL_DESC_PLACEHOLDER: "Description coming soon.",
  DETAIL_YOUR_RATING: "Your rating",
  // Profile / Shelf
  PROFILE_STAT_TOTAL: "Total books",
  PROFILE_STAT_READ: "Read",
  PROFILE_STAT_READING: "Reading",
  PROFILE_STAT_LISTENED: "Listened",
  PROFILE_GOAL_LABEL: "Goal 2026",
  PROFILE_GOAL_EDIT: "Edit goal",
  PROFILE_GOAL_SAVE: "Save",
  PROFILE_GOAL_CANCEL: "Cancel",
  PROFILE_GOAL_INPUT_LABEL: "Yearly reading goal",
  PROFILE_SETTINGS: "Settings",
  PROFILE_FRIEND_LABEL: "View a friend's shelf:",
  PROFILE_FRIEND_PLACEHOLDER: "enter email...",
  PROFILE_FRIEND_BTN: "View shelf",
  PROFILE_REMOVE: "Remove",
  PROFILE_REMOVE_CONFIRM_TITLE: "Remove this book?",
  PROFILE_REMOVE_CONFIRM_TEXT: "It will be removed from your shelf.",
  PROFILE_REMOVE_CONFIRM_BTN: "Remove",
  PROFILE_REMOVE_CANCEL_BTN: "Cancel",
  PROFILE_EMPTY_SHELF: "No books in this category.",
  PROFILE_TITLE: "My Shelf",
  // Settings page
  SETTINGS_TITLE: "Profile settings",
  SETTINGS_SUBTITLE: "Update your name, avatar and notifications",
  SETTINGS_BACK: "← Back to my shelf",
  SETTINGS_LABEL_DISPLAY_NAME: "Display name",
  SETTINGS_PLACEHOLDER_DISPLAY_NAME: "How should we call you?",
  SETTINGS_DISPLAY_NAME_ERROR: "Display name must be 60 characters or fewer.",
  SETTINGS_LABEL_AVATAR: "Avatar image",
  SETTINGS_AVATAR_UPLOAD: "Upload avatar",
  SETTINGS_AVATAR_UPLOADING: "Uploading...",
  SETTINGS_LABEL_NOTIFY: "Email notifications",
  SETTINGS_NOTIFY_HINT: "Receive product updates by email",
  SETTINGS_SAVE: "Save changes",
  SETTINGS_SAVED: "Profile updated",
  SETTINGS_SAVE_ERROR: "Could not save your profile. Please try again.",
  SETTINGS_AVATAR_SUCCESS: "Avatar updated",
  // Shelf Tabs
  SHELF_TAB_ALL: "All",
  // Search Modal
  SEARCH_PLACEHOLDER: "Search by title or author...",
  SEARCH_CLOSE: "Close",
  SEARCH_SUGGESTED_LABEL: "Suggested",
  SEARCH_RESULTS_LABEL: "Results",
  SEARCH_EMPTY: "No results found.",
  SEARCH_ADD: "+ Add",
  // Create Product
  CREATE_TITLE: "Add new book",
  CREATE_BTN: "Create book",
  CREATE_LABEL_AUTHOR: "Author name",
  CREATE_LABEL_TITLE: "Book title",
  CREATE_LABEL_GENRE: "Genre",
  CREATE_LABEL_IMAGE: "Cover image",
  CREATE_LABEL_SRC: "Image name",
  CREATE_PLACEHOLDER_AUTHOR: "Author name",
  CREATE_PLACEHOLDER_TITLE: "Book title",
  CREATE_PLACEHOLDER_GENRE: "Genre",
  // Support Chat
  SUPPORT_TITLE: "Support Chat",
  // Search By Email
  SEARCH_EMAIL_TITLE: "Viewing shelf for",
  // Common
  COMMON_LOADING: "Loading...",
  COMMON_COMING_SOON: "Coming soon",
  COMMON_NOT_FOUND_TITLE: "404",
  COMMON_NOT_FOUND_SUBTITLE: "Page not found",
  COMMON_BACK_TO_HOME: "Back to home",
  COMMON_PLACEHOLDER_VALUE: "—",
  COMMON_SEARCH_LABEL: "Search",
  // Toast messages
  TOAST_LOGIN_SUCCESS: "Successfully logged in",
  TOAST_REGISTER_SUCCESS: "Account created — check your email",
  TOAST_IMAGE_SUCCESS: "Cover image uploaded successfully",
  TOAST_REMOVE_SUCCESS: "Book removed from your shelf",
  TOAST_MAGIC_LINK_SENT: "Check your email for the sign-in link",
  TOAST_MAGIC_ENTER_EMAIL: "Enter your email first",
  TOAST_GENERIC_ERROR: "Something went wrong. Please try again.",
  // Magic link verify screen
  AUTH_MAGIC_VERIFYING: "Signing you in...",
  AUTH_MAGIC_SUCCESS: "Signed in successfully",
  AUTH_MAGIC_ERROR: "This sign-in link is invalid or has expired.",
};
